// tslint:disable
/**
 * order-domain
 * This is a API-Documentation for the order-domain. It serves as a data-contract.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: frederick.behringer@smail.inf.h-brs.de
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

export * from "./api";
export * from "./configuration";
